### ISSUE TITLE
Bracket match highlighting missing from Code Mirror

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#10]
Critical functionality missing.

**Comment by justparking** [comment]
example on "old" nodel:
![image](https://user-images.githubusercontent.com/5266533/57356700-7efbe480-71b4-11e9-9f6b-b45dafc0306f.png)

example on "new" nodel:
![image](https://user-images.githubusercontent.com/5266533/57356711-8a4f1000-71b4-11e9-9901-6a2b34011994.png)

**Comment by mcartmel** [comment]
Added
