### ISSUE TITLE
nodeURLs should return all addresses

### ISSUE THREAD

**Issue by mcartmel** [justparking/feature_nodeluiunify#11]
Currently, nodeURLs will return only one address for each node. In a multihomed environment, some nodes may have multiple addresses on different subnets. 

The UI code can now handle multiple addresses and will determine which one is reachable from the current location. Just need nodeURLs to return all possible addresses for this to work.

**Comment by justparking** [comment]
The latest code now includes all multi-address nodes, that the same node names (reduced version) running on multiple hosts, as well as the same node across multiple interfaces.
