### ISSUE TITLE
Default recipe should be the XML parser (frontend)?

### ISSUE THREAD

**Issue by mcartmel** [justparking/feature_nodeluiunify#12]
Since Nodel will now include the "frontend" recipe as part of core, should someone still need to pick the 'frontend' recipe when creating a new node, or should it be assumed? 

If it is assumed, then the default script.py used for a 'blank' node should be the XML parser script.py. 

Not sure if this is the correct way of handling this, just creating an issue for discussion.

**Comment by mcartmel** [comment]
Need to create 'new' frontend recipe which has the additional content files removed (now in core).

**Comment by justparking** [comment]
Assigned to Mic to handle likely backwards/forwards compatibility.

**Comment by mcartmel** [comment]
Proposed solution to preserving existing frontend nodes, maintaining existing links to those frontends by utilising redirection:

### Preperation
Move the contents of 'content' to a subfolder (eg. 'ui')

### HTML frontend

If the frontend was a 'HTML' file, create a new file in the 'content' folder with the same name as the original file and insert this code (replacing 'frontend.htm' with the name of the original file):
```
<!doctype html>
<html>
  <head>
    <meta http-equiv="refresh" content="0;url=ui/frontend.htm"/>
  </head>
</html>
```

### XML frontend

If the frontend was a 'XML' file, create a new file in the 'content' folder with the same name as the original file and insert this code:
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="redirect.xsl"?>
<_/>
```
Then create a 'redirect.xsl' file and insert this code (replacing 'index.xml' with the name of the original file, if required)
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:template match="/">
    <html lang="en" xsl:version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
      <head>
        <meta http-equiv="refresh" content="0;url=ui/index.xml"/>
      </head>
    </html>
  </xsl:template>
</xsl:stylesheet>
```
Finally, update 'script.py' to point to the new location of the original XML file:
```
...
indexFile = os.path.join(workingDir, 'content', 'ui/index.xml')
...
```

**Comment by justparking** [comment]
This is very complicated.

**Comment by mcartmel** [comment]
Consider this a (not very complicated) documented workaround if any issues are encountered.

I've made modifications to minimise the chance of clashes in 12f76f7, but clashes could still occur depending on how someone has decided to utilise the existing Frontend recipe or create custom interface code.

I recommend testing, and then implementing the workaround if a problem found.
