### ISSUE TITLE
Some JS dependencies causing alerts by github

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#14]
As owner, I get these warnings when I log into github:
![image](https://user-images.githubusercontent.com/5266533/59153805-57938280-8aa6-11e9-93bd-efa6cc2fbe83.png)

Details are in this URL - https://github.com/justparking/feature_nodeluiunify/network/alerts - shown here:

![image](https://user-images.githubusercontent.com/5266533/59153811-87db2100-8aa6-11e9-8bc5-c73127fa7240.png)

We'd probably want to get those dependencies updated before we move this code back to the main `/museumsvictoria/nodel` repo.

**Comment by mcartmel** [comment]
Updated dependencies to resolve the security concerns.

**Comment by justparking** [comment]
Not sure if this is new or not, **shelljs** (can you access https://github.com/justparking/feature_nodeluiunify/network/alerts?q=is%3Aopen ?)

![image](https://user-images.githubusercontent.com/5266533/60494205-aae9a100-9cf1-11e9-9ab2-209202e428bc.png)

**Comment by mcartmel** [comment]
@justparking I get a 404 on that link sorry.

I believe this library was being introduced as a dependency of jshint which was required for lodash previously. I've removed this as a new method is used for building lodash now, so hopefully the alert is now resolved with 70786ec.

**Comment by justparking** [comment]
Alerts all gone now.
