### ISSUE TITLE
Navigation now leads to tab hell!

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#18]
Almost all navigation clicks now create new tabs. This is leading me to multi-tab hell very quickly.

There should be very few things that open new tabs. Remember the user already has at least three different ways to open things in new tabs:
* clicking mouse middle button,
*  right-clicking "open link in new tab" 
* pressing Ctrl and clicking the link.

Why not leave it to them?

If nothing else, jumping between node and nodes list and back again should not create new tabs for every operation.

@scroix Thoughts?

**Comment by justparking** [comment]
I include Toolkit and Diagnostics in this too.

**Comment by mcartmel** [comment]
@justparking I think you're telling me you don't like tabs?

**Comment by mcartmel** [comment]
Default behaviour changed in 9f54ac6
