### ISSUE TITLE
Adjusting action/signal values then calling/emitting does not always work

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#25]
Often it takes hitting the Action call button or Signal emit button twice before anything will actually happen.

**Comment by justparking** [comment]
I'm noticing this with Save buttons too.

**Comment by mcartmel** [comment]
@justparking Do you have a particular node that does this? I haven't been able to replicate the problem as yet.

**Comment by justparking** [comment]
I haven't seen this for a while.
