### ISSUE TITLE
Unable to fill in bindings

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#29]
Getting error: 

![image](https://user-images.githubusercontent.com/5266533/60632071-979c1a00-9e46-11e9-97b0-84a111a9b61a.png)

**Comment by mcartmel** [comment]
I suspect this was caused by some un-escaped characters going into the regex. Can you test?

**Comment by mcartmel** [comment]
I've tested and it seems to be working fine.

**Comment by justparking** [comment]
No, this still occurs. Have msged you example node address.

**Comment by justparking** [comment]
So have identified at least one bracket related issue e.g. `Blah Blah` vs `Blah Blah (status group` node naming.

**Comment by mcartmel** [comment]
Just to note, this is not related to the initial error that was reported (which is fixed). This relates to the handling of nodes with parentheses in the name.
