### ISSUE TITLE
Background presence detection spoils Javascript console

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#30]
Can't tell if there's a legitimate error or not.

e.g. I got this just looking at a Dashboard node even though that node's page does not access any other IP addresses.

![image](https://user-images.githubusercontent.com/5266533/60632258-05951100-9e48-11e9-83f9-ff621e0b512a.png)

**Comment by mcartmel** [comment]
CORS errors cannot be trapped by Javascript in the browser (try catch doesn't trap it). The Concierge panels are all preventing requests from other sources (whether that is because of the Auth requirement, I'm not sure).
