### ISSUE TITLE
"arg" title is redundant

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#36]
It'd look **much** cleaner if "arg" titles are removed. I don't think they're needed.

**Comment by justparking** [comment]
Still there for these:

![image](https://user-images.githubusercontent.com/5266533/60854333-365bb880-a243-11e9-993b-d022726c7a1d.png)

The big blue box implies it's an arg, surely?

**Comment by mcartmel** [comment]
@justparking It needs some sort of title for the dropdown to work. I guess I could just use a space? Let me see what it looks like.
