### ISSUE TITLE
action/signal json formatting gone wrong

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#38]
For example:
![image](https://user-images.githubusercontent.com/5266533/60778722-617ad500-a17b-11e9-8c0c-cbc820c46a3e.png)

Something to do with length?

**Comment by justparking** [comment]
Also 
![image](https://user-images.githubusercontent.com/5266533/60778773-9129dd00-a17b-11e9-90f1-36f108bee844.png)

**Comment by mcartmel** [comment]
Yes, the length is limited.
