### ISSUE TITLE
Multi-select bindings

### ISSUE THREAD

**Issue by mcartmel** [justparking/feature_nodeluiunify#47]
It would be nice to be able to shift-click the checkboxes in bindings to select a range.

**Comment by justparking** [comment]
I couldn't get this to work. Can you explain how it's supposed to?

**Comment by mcartmel** [comment]
You tick the first box, then hold shift and click the last box. It should tick all the boxes in-between.

**Comment by justparking** [comment]
k, cool. Must have had an old version even though I made sure it was the latest.
