### ISSUE TITLE
UI needs to be buildable

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#5]
Large component.css files should not be checked into the main project.

Nor .min files, etc.

If you can document the build-steps you're using, I can add it to the main build script so everything can be built from basic elements.

**Comment by mcartmel** [comment]
Process is essentially this. I'll elaborate further once I've committed the code.

Install required tools
apt-get install nodejs grunt-cli

Download dependencies (in package.json)
npm install

Build
grunt build

**Comment by mcartmel** [comment]
Source files have now been committed (https://github.com/justparking/feature_nodeluiunify/commit/3caf3fab816dcc37bdd8bcaf597d337765180c1b). @justparking let me know if you need help with the build step.

**Comment by justparking** [comment]
I needed at least these additional steps:
* `npm install grunt --save-dev`
then I can run:
* `grunt`

but then it wants to download  phantomjs but normally stalls.
```
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to H:\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...
  [=================================-------] 83%^CTerminate batch job (Y/N)? y
```

then I run `grunt` again and I think it works, finishing off with:
```
Running "uglify:applib" (uglify) task
>> 1 file created 2.75 MB → 858.3 kB

Done, without errors.
```
Presuming I can pre-install phantomjs, but what about the ``npm install grunt --save-dev` - is that considered a normal way to kick off a grunt build?

Also, the build output folder needs to be a subfolder within the `build` folder because there are other build artifacts that go there.

Is it as simple as just a search & replace within the Gruntfile.js from `build/` to `build/gruntbuild` or are there other references I need to look out for?

**Comment by justparking** [comment]
a related release is available:

https://github.com/justparking/feature_nodeluiunify/releases/tag/r4

**Comment by justparking** [comment]
FYI, `temp/lodash.build.js` appeared to be self-generating so I removed it from the repo.

It's questionable whether `package-lock.json` should be checked in either. Whether it there or not has not affected my ability to build the project.

**Comment by mcartmel** [comment]
Ok, so made a few changes here so it's hopefully smoother. Tested on a local Ubuntu instance from scratch. Also, the requirement to download phantomjs has been corrected.

Install the latest NodeJS using the latest builds, using instructions from [here](https://github.com/nodesource/distributions/blob/master/README.md#debinstall):
```
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
```
Then install grunt and lodash cli using npm:
```
sudo npm i -g lodash-cli grunt-cli
```
Finally, download dependencies and build:
```
npm install
grunt
```

**Comment by justparking** [comment]
This has been incorporated into the main build script, more or less. Closing...
