### ISSUE TITLE
"Save script - check console - repeat" workflow missing

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#6]
When constantly editing a script, you have to flick views after every save to check the console output.

It feels like that part of the user experience has been hobbled.

For example, I just quickly edited a script.py, pressed save, and nothing happened. I had to flick back to the console and notice the syntax error I made. I then flick back to make more changes.

**Comment by mcartmel** [comment]
I've moved the console to the config page. Do you think this will work better?

**Comment by justparking** [comment]
I guess we'll continually assess workflow. Closing for now.
